# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import meeting_pb2 as meeting__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in meeting_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeetingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BookMeeting = channel.unary_unary(
                '/MeetingService/BookMeeting',
                request_serializer=meeting__pb2.MeetingRequest.SerializeToString,
                response_deserializer=meeting__pb2.BookResponse.FromString,
                _registered_method=True)
        self.QueryByID = channel.unary_unary(
                '/MeetingService/QueryByID',
                request_serializer=meeting__pb2.QueryByIDRequest.SerializeToString,
                response_deserializer=meeting__pb2.Meeting.FromString,
                _registered_method=True)
        self.QueryByOrganizer = channel.unary_unary(
                '/MeetingService/QueryByOrganizer',
                request_serializer=meeting__pb2.QueryByOrganizerRequest.SerializeToString,
                response_deserializer=meeting__pb2.MeetingList.FromString,
                _registered_method=True)
        self.CancelMeeting = channel.unary_unary(
                '/MeetingService/CancelMeeting',
                request_serializer=meeting__pb2.CancelRequest.SerializeToString,
                response_deserializer=meeting__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.GetFreeRooms = channel.unary_unary(
                '/MeetingService/GetFreeRooms',
                request_serializer=meeting__pb2.EmptyRequest.SerializeToString,
                response_deserializer=meeting__pb2.RoomList.FromString,
                _registered_method=True)


class MeetingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BookMeeting(self, request, context):
        """预约会议
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryByID(self, request, context):
        """查询会议 传入id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryByOrganizer(self, request, context):
        """查询所有会议 传入组织者姓名
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelMeeting(self, request, context):
        """取消会议
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFreeRooms(self, request, context):
        """空闲会议室查询
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeetingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BookMeeting': grpc.unary_unary_rpc_method_handler(
                    servicer.BookMeeting,
                    request_deserializer=meeting__pb2.MeetingRequest.FromString,
                    response_serializer=meeting__pb2.BookResponse.SerializeToString,
            ),
            'QueryByID': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryByID,
                    request_deserializer=meeting__pb2.QueryByIDRequest.FromString,
                    response_serializer=meeting__pb2.Meeting.SerializeToString,
            ),
            'QueryByOrganizer': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryByOrganizer,
                    request_deserializer=meeting__pb2.QueryByOrganizerRequest.FromString,
                    response_serializer=meeting__pb2.MeetingList.SerializeToString,
            ),
            'CancelMeeting': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelMeeting,
                    request_deserializer=meeting__pb2.CancelRequest.FromString,
                    response_serializer=meeting__pb2.CancelResponse.SerializeToString,
            ),
            'GetFreeRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFreeRooms,
                    request_deserializer=meeting__pb2.EmptyRequest.FromString,
                    response_serializer=meeting__pb2.RoomList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MeetingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MeetingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeetingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BookMeeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeetingService/BookMeeting',
            meeting__pb2.MeetingRequest.SerializeToString,
            meeting__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeetingService/QueryByID',
            meeting__pb2.QueryByIDRequest.SerializeToString,
            meeting__pb2.Meeting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryByOrganizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeetingService/QueryByOrganizer',
            meeting__pb2.QueryByOrganizerRequest.SerializeToString,
            meeting__pb2.MeetingList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelMeeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeetingService/CancelMeeting',
            meeting__pb2.CancelRequest.SerializeToString,
            meeting__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFreeRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MeetingService/GetFreeRooms',
            meeting__pb2.EmptyRequest.SerializeToString,
            meeting__pb2.RoomList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
