# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meeting.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'meeting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmeeting.proto\"\x0e\n\x0c\x45mptyRequest\"\x18\n\x04Room\x12\x10\n\x08roomName\x18\x01 \x01(\t\" \n\x08RoomList\x12\x14\n\x05rooms\x18\x01 \x03(\x0b\x32\x05.Room\"\x89\x01\n\x07Meeting\x12\x11\n\tmeetingID\x18\x01 \x01(\t\x12\x11\n\torganizer\x18\x02 \x01(\t\x12\x10\n\x08roomName\x18\x03 \x01(\t\x12\r\n\x05topic\x18\x04 \x01(\t\x12\x11\n\tstartTime\x18\x05 \x01(\t\x12\x0f\n\x07\x65ndTime\x18\x06 \x01(\t\x12\x13\n\x0bpeopleCount\x18\x07 \x01(\x05\"+\n\x0eMeetingRequest\x12\x19\n\x07meeting\x18\x01 \x01(\x0b\x32\x08.Meeting\"2\n\x0c\x42ookResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tmeetingID\x18\x02 \x01(\t\"%\n\x10QueryByIDRequest\x12\x11\n\tmeetingID\x18\x01 \x01(\t\"0\n\x17QueryByOrganizerRequest\x12\x15\n\rorganizerName\x18\x01 \x01(\t\")\n\x0bMeetingList\x12\x1a\n\x08meetings\x18\x01 \x03(\x0b\x32\x08.Meeting\"\"\n\rCancelRequest\x12\x11\n\tmeetingID\x18\x01 \x01(\t\"!\n\x0e\x43\x61ncelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x81\x02\n\x0eMeetingService\x12-\n\x0b\x42ookMeeting\x12\x0f.MeetingRequest\x1a\r.BookResponse\x12(\n\tQueryByID\x12\x11.QueryByIDRequest\x1a\x08.Meeting\x12:\n\x10QueryByOrganizer\x12\x18.QueryByOrganizerRequest\x1a\x0c.MeetingList\x12\x30\n\rCancelMeeting\x12\x0e.CancelRequest\x1a\x0f.CancelResponse\x12(\n\x0cGetFreeRooms\x12\r.EmptyRequest\x1a\t.RoomListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meeting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=17
  _globals['_EMPTYREQUEST']._serialized_end=31
  _globals['_ROOM']._serialized_start=33
  _globals['_ROOM']._serialized_end=57
  _globals['_ROOMLIST']._serialized_start=59
  _globals['_ROOMLIST']._serialized_end=91
  _globals['_MEETING']._serialized_start=94
  _globals['_MEETING']._serialized_end=231
  _globals['_MEETINGREQUEST']._serialized_start=233
  _globals['_MEETINGREQUEST']._serialized_end=276
  _globals['_BOOKRESPONSE']._serialized_start=278
  _globals['_BOOKRESPONSE']._serialized_end=328
  _globals['_QUERYBYIDREQUEST']._serialized_start=330
  _globals['_QUERYBYIDREQUEST']._serialized_end=367
  _globals['_QUERYBYORGANIZERREQUEST']._serialized_start=369
  _globals['_QUERYBYORGANIZERREQUEST']._serialized_end=417
  _globals['_MEETINGLIST']._serialized_start=419
  _globals['_MEETINGLIST']._serialized_end=460
  _globals['_CANCELREQUEST']._serialized_start=462
  _globals['_CANCELREQUEST']._serialized_end=496
  _globals['_CANCELRESPONSE']._serialized_start=498
  _globals['_CANCELRESPONSE']._serialized_end=531
  _globals['_MEETINGSERVICE']._serialized_start=534
  _globals['_MEETINGSERVICE']._serialized_end=791
# @@protoc_insertion_point(module_scope)
